PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY, name TEXT NOT NULL, login TEXT NOT NULL UNIQUE, city TEXT NOT NULL, age INTEGER NOT NULL CHECK(age BETWEEN 18 AND 120), salt TEXT NOT NULL, password_hash TEXT NOT NULL, coins INTEGER NOT NULL DEFAULT 1000 CHECK(coins>=0), is_admin INTEGER NOT NULL DEFAULT 0 CHECK(is_admin IN (0,1)), created INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), expires INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS sessions_user ON sessions(user_id);
CREATE TABLE IF NOT EXISTS rooms(id TEXT PRIMARY KEY, name TEXT NOT NULL, owner TEXT REFERENCES users(id), youtube TEXT, created INTEGER NOT NULL);
INSERT OR IGNORE INTO rooms(id,name,created) VALUES('lobby','Mersin Meydanı',unixepoch());
CREATE TABLE IF NOT EXISTS presence(user_id TEXT PRIMARY KEY REFERENCES users(id), room_id TEXT NOT NULL REFERENCES rooms(id), seat INTEGER CHECK(seat BETWEEN 0 AND 8), seen INTEGER NOT NULL, UNIQUE(room_id,seat));
CREATE INDEX IF NOT EXISTS presence_room ON presence(room_id);
CREATE TABLE IF NOT EXISTS messages(id INTEGER PRIMARY KEY AUTOINCREMENT,room_id TEXT NOT NULL REFERENCES rooms(id),user_id TEXT REFERENCES users(id),name TEXT NOT NULL,kind TEXT NOT NULL,text TEXT NOT NULL,created INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS messages_room ON messages(room_id,id);
CREATE TRIGGER IF NOT EXISTS presence_join AFTER INSERT ON presence BEGIN INSERT INTO messages(room_id,user_id,name,kind,text,created) SELECT NEW.room_id,NEW.user_id,name,'join','odaya katıldı',unixepoch() FROM users WHERE id=NEW.user_id; END;
CREATE TRIGGER IF NOT EXISTS presence_leave AFTER DELETE ON presence BEGIN INSERT INTO messages(room_id,user_id,name,kind,text,created) SELECT OLD.room_id,OLD.user_id,name,'leave','odadan ayrıldı',unixepoch() FROM users WHERE id=OLD.user_id; END;
CREATE TABLE IF NOT EXISTS rate_limits(key TEXT PRIMARY KEY, count INTEGER NOT NULL, expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS gifts(id TEXT PRIMARY KEY, sender TEXT NOT NULL REFERENCES users(id), recipient TEXT NOT NULL REFERENCES users(id), room_id TEXT NOT NULL REFERENCES rooms(id), gift TEXT NOT NULL, cost INTEGER NOT NULL, created INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS signals(id TEXT PRIMARY KEY, room_id TEXT NOT NULL REFERENCES rooms(id), from_user TEXT NOT NULL REFERENCES users(id), to_user TEXT NOT NULL REFERENCES users(id), payload TEXT NOT NULL, created INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS signals_recipient ON signals(to_user,room_id,created);
CREATE TABLE IF NOT EXISTS friendships(id TEXT PRIMARY KEY, requester TEXT NOT NULL REFERENCES users(id), recipient TEXT NOT NULL REFERENCES users(id), status TEXT NOT NULL DEFAULT 'pending', created INTEGER NOT NULL, UNIQUE(requester,recipient));
CREATE TABLE IF NOT EXISTS private_messages(id INTEGER PRIMARY KEY AUTOINCREMENT,sender TEXT NOT NULL REFERENCES users(id),recipient TEXT NOT NULL REFERENCES users(id),text TEXT NOT NULL,created INTEGER NOT NULL,read_at INTEGER);
CREATE TABLE IF NOT EXISTS reports(id TEXT PRIMARY KEY,reporter TEXT NOT NULL REFERENCES users(id),target TEXT NOT NULL REFERENCES users(id),reason TEXT NOT NULL,created INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'open');
CREATE TABLE IF NOT EXISTS blocks(blocker TEXT NOT NULL REFERENCES users(id),blocked TEXT NOT NULL REFERENCES users(id),created INTEGER NOT NULL,PRIMARY KEY(blocker,blocked));
CREATE TABLE IF NOT EXISTS room_moderation(room_id TEXT NOT NULL REFERENCES rooms(id),user_id TEXT NOT NULL REFERENCES users(id),action TEXT NOT NULL,until_at INTEGER,reason TEXT,created INTEGER NOT NULL,PRIMARY KEY(room_id,user_id,action));
CREATE TABLE IF NOT EXISTS daily_rewards(user_id TEXT PRIMARY KEY REFERENCES users(id),last_claim INTEGER NOT NULL,streak INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS badges(user_id TEXT NOT NULL REFERENCES users(id),badge TEXT NOT NULL,created INTEGER NOT NULL,PRIMARY KEY(user_id,badge));
CREATE TABLE IF NOT EXISTS daily_visitors(day TEXT NOT NULL,visitor_hash TEXT NOT NULL,created INTEGER NOT NULL,PRIMARY KEY(day,visitor_hash));
CREATE TABLE IF NOT EXISTS user_profiles(user_id TEXT PRIMARY KEY REFERENCES users(id),bio TEXT NOT NULL DEFAULT '',updated INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS room_settings(room_id TEXT PRIMARY KEY REFERENCES rooms(id),description TEXT NOT NULL DEFAULT '',access_code_hash TEXT,capacity INTEGER NOT NULL DEFAULT 9 CHECK(capacity BETWEEN 2 AND 9));
CREATE TABLE IF NOT EXISTS events(id TEXT PRIMARY KEY,room_id TEXT NOT NULL REFERENCES rooms(id),creator TEXT NOT NULL REFERENCES users(id),title TEXT NOT NULL,starts INTEGER NOT NULL,created INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS invitations(id TEXT PRIMARY KEY,event_id TEXT REFERENCES events(id),room_id TEXT NOT NULL REFERENCES rooms(id),sender TEXT NOT NULL REFERENCES users(id),recipient TEXT NOT NULL REFERENCES users(id),created INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'pending');
CREATE TABLE IF NOT EXISTS room_profiles(room_id TEXT PRIMARY KEY REFERENCES rooms(id),image_url TEXT,updated INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS room_progress(room_id TEXT PRIMARY KEY REFERENCES rooms(id),gift_xp INTEGER NOT NULL DEFAULT 0 CHECK(gift_xp>=0),level INTEGER NOT NULL DEFAULT 1 CHECK(level>=1),updated INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS room_policies(room_id TEXT PRIMARY KEY REFERENCES rooms(id),description TEXT NOT NULL DEFAULT '',rules TEXT NOT NULL DEFAULT '',banned_words TEXT NOT NULL DEFAULT '',access_code_hash TEXT,category TEXT NOT NULL DEFAULT 'Sohbet',speaker_only INTEGER NOT NULL DEFAULT 0 CHECK(speaker_only IN (0,1)),theme TEXT NOT NULL DEFAULT 'lavender',updated INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS notifications(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),kind TEXT NOT NULL,text TEXT NOT NULL,link TEXT,created INTEGER NOT NULL,read_at INTEGER);
CREATE INDEX IF NOT EXISTS notifications_user ON notifications(user_id,created DESC);
CREATE TABLE IF NOT EXISTS profile_images(user_id TEXT PRIMARY KEY REFERENCES users(id),image_url TEXT,updated INTEGER NOT NULL);
