import express from 'express';import{createServer}from'node:http';import{Server}from'socket.io';import pg from 'pg';import{randomUUID,createHash}from'node:crypto';
const app=express(),server=createServer(app),io=new Server(server,{cors:{origin:true}}),users=new Map(),sessions=new Map(),rooms=new Map(),presence=new Map(),msgs=new Map(),signals=new Map(),notifications=new Map(),friends=new Map(),db=process.env.DATABASE_URL?new pg.Pool({connectionString:process.env.DATABASE_URL}):null;let mid=0;
const h=x=>createHash('sha256').update(String(x)).digest('hex'),key=x=>String(x||'').trim().toLocaleLowerCase('tr-TR'),prof=u=>({id:u.id,name:u.name,emoji:u.emoji||'🙂',city:u.city,age:u.age,coins:u.coins,avatar:u.avatar||'',xp:u.xp||0,level:1+Math.floor((u.xp||0)/1000)});const fail=(r,s,e)=>r.status(s).json({error:e});const me=q=>users.get(sessions.get((q.get('authorization')||'').replace(/^Bearer /,'')));
const aid=randomUUID();users.set(aid,{id:aid,name:'admin',login:'admin',city:'Mersin',age:18,password:h('4321'),coins:1000,emoji:'🛡️',xp:0,is_admin:true});
async function saveUser(u){if(!db)return;await db.query('INSERT INTO users(id,name,login,city,age,password,coins,emoji,avatar,xp) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,city=EXCLUDED.city,age=EXCLUDED.age,password=EXCLUDED.password,coins=EXCLUDED.coins,emoji=EXCLUDED.emoji,avatar=EXCLUDED.avatar,xp=EXCLUDED.xp',[u.id,u.name,u.login,u.city,u.age,u.password,u.coins,u.emoji,u.avatar||'',u.xp||0])}
async function boot(){if(db){await db.query('CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,name TEXT NOT NULL,login TEXT UNIQUE NOT NULL,city TEXT NOT NULL,age INTEGER NOT NULL,password TEXT NOT NULL,coins INTEGER NOT NULL,emoji TEXT NOT NULL,avatar TEXT NOT NULL DEFAULT \'\',xp INTEGER NOT NULL DEFAULT 0)');const admin=users.get(aid);await db.query('INSERT INTO users(id,name,login,city,age,password,coins,emoji,avatar,xp) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(login) DO NOTHING',[admin.id,admin.name,admin.login,admin.city,admin.age,admin.password,admin.coins,admin.emoji,'',0]);const rows=(await db.query('SELECT * FROM users')).rows;users.clear();for(const u of rows)users.set(u.id,{...u,is_admin:u.login==='admin'})}server.listen(process.env.PORT||3000,()=>console.log('TopTown Node.js ready'))}
app.use(express.json({limit:'200kb'}));app.use(express.static('public'));app.get('/api/health',(_,r)=>r.json({ok:true,runtime:'node',rooms:rooms.size}));
app.post('/api/register',async(q,r)=>{let b=q.body||{},k=key(b.name);if(k.length<2||!String(b.city||'').trim()||+b.age<18||+b.age>120||String(b.password||'').length<4)return fail(r,400,'Alanları kontrol edin.');if([...users.values()].some(u=>u.login===k))return fail(r,409,'Bu isim kullanılıyor.');let id=randomUUID(),u={id,name:String(b.name).trim(),login:k,city:String(b.city).trim(),age:+b.age,password:h(b.password),coins:1000,emoji:'🙂',xp:0};try{await saveUser(u)}catch{return fail(r,409,'Bu isim kullanılıyor.')}users.set(id,u);let t=randomUUID()+randomUUID();sessions.set(t,id);r.json({token:t,user:prof(u)})});
app.post('/api/login',(q,r)=>{let u=[...users.values()].find(x=>x.login===key(q.body?.name));if(!u||u.password!==h(q.body?.password||''))return fail(r,401,'İsim veya şifre hatalı.');let t=randomUUID()+randomUUID();sessions.set(t,u.id);r.json({token:t,user:prof(u)})});
app.use('/api',(q,r,n)=>{if(['/health','/login','/register'].includes(q.path))return n();q.user=me(q);if(!q.user)return fail(r,401,'Oturum sona erdi. Tekrar giriş yapın.');n()});
app.get('/api/me',(q,r)=>r.json({user:prof(q.user),admin:!!q.user.is_admin}));app.get('/api/rooms',(_,r)=>{r.set('Cache-Control','no-store');r.json([...rooms.values()].map(x=>({...x,online:[...presence.values()].filter(p=>p.room===x.id).length}))) });app.post('/api/rooms',(q,r)=>{let n=String(q.body?.name||'').trim();if(n.length<2)return fail(r,400,'Oda adı gerekli.');let id=randomUUID();rooms.set(id,{id,name:n,owner:q.user.id,youtube:null});msgs.set(id,[]);r.json({id})});
app.post('/api/join',(q,r)=>{if(!rooms.has(q.body?.room))return fail(r,404,'Oda bulunamadı.');presence.set(q.user.id,{room:q.body.room,seat:null});r.json({ok:true})});app.post('/api/leave',(q,r)=>{presence.delete(q.user.id);r.json({ok:true})});app.get('/api/state',(q,r)=>{let p=presence.get(q.user.id),room=rooms.get(p?.room);if(!room)return fail(r,409,'Önce bir odaya katılın.');let after=+q.query.after||0,people=[...presence].filter(([,x])=>x.room===room.id).map(([id,x])=>({...prof(users.get(id)),seat:x.seat}));r.json({room,people,messages:(msgs.get(room.id)||[]).filter(x=>x.id>after),coins:q.user.coins})});
app.post('/api/message',(q,r)=>{let p=presence.get(q.user.id),t=String(q.body?.text||'').trim();if(!p||!t)return fail(r,400,'Önce odaya katılıp mesaj yazın.');let a=msgs.get(p.room)||[];a.push({id:++mid,name:q.user.name,kind:'chat',text:t});msgs.set(p.room,a);r.json({ok:true})});app.post('/api/seat',(q,r)=>{let p=presence.get(q.user.id);if(!p)return fail(r,409,'Önce odaya katılın.');p.seat=q.body.seat;r.json({ok:true})});app.post('/api/profile',(q,r)=>{q.user.emoji=String(q.body?.emoji||'🙂');if(typeof q.body?.avatar==='string'&&q.body.avatar.length<=200000)q.user.avatar=q.body.avatar;r.json({user:prof(q.user)})});app.post('/api/gift',(q,r)=>{const costs={rose:30,cake:120,rocket:300,crown:800},gift=String(q.body?.gift||''),cost=costs[gift],to=users.get(String(q.body?.recipient||''));if(!cost||!to||to.id===q.user.id||presence.get(to.id)?.room!==presence.get(q.user.id)?.room)return fail(r,400,'Hediye alıcısını odadan seçin.');if(q.user.coins<cost)return fail(r,400,'Yeterli jeton yok.');q.user.coins-=cost;to.coins+=cost;to.xp=(to.xp||0)+cost;q.user.xp=(q.user.xp||0)+Math.ceil(cost/2);const list=notifications.get(to.id)||[];list.unshift({text:q.user.name+' sana '+gift+' hediyesi gönderdi.'});notifications.set(to.id,list.slice(0,30));r.json({ok:true,coins:q.user.coins})});app.post('/api/youtube',(q,r)=>{const p=presence.get(q.user.id),url=String(q.body?.url||'').trim();if(!p)return fail(r,409,'Önce odaya katılın.');const id=url?(url.match(/(?:v=|youtu\.be\/|embed\/)([\w-]{11})/)||[])[1]:null;if(url&&!id)return fail(r,400,'Geçerli bir YouTube bağlantısı girin.');rooms.get(p.room).youtube=id||null;r.json({ok:true})});app.get('/api/notifications',(q,r)=>r.json({items:notifications.get(q.user.id)||[]}));app.get('/api/friends',(q,r)=>r.json([...(friends.get(q.user.id)||[])].map(id=>prof(users.get(id))).filter(Boolean)));app.post('/api/logout',(q,r)=>{presence.delete(q.user.id);r.json({ok:true})});app.get('/api/signal',(q,r)=>{let a=signals.get(q.user.id)||[];signals.set(q.user.id,[]);r.json(a)});app.post('/api/signal',(q,r)=>{let to=String(q.body?.to||''),p=q.body?.payload,from=presence.get(q.user.id),dest=presence.get(to);if(!p||!to||!from||from.room!==dest?.room)return fail(r,400,'Sinyal alıcısı odada değil.');let a=signals.get(to)||[];a.push({from:q.user.id,payload:p});signals.set(to,a);r.json({ok:true})});app.get('/api/admin',(q,r)=>q.user.is_admin?r.json({summary:{users:users.size,rooms:rooms.size,online:presence.size},users:[...users.values()].map(u=>({...prof(u),is_admin:u.is_admin}))}):fail(r,403,'Yönetici yetkisi gerekiyor.'));
boot().catch(error=>{console.error('PostgreSQL başlatılamadı',error);process.exit(1)});
