CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,name TEXT NOT NULL,login TEXT UNIQUE NOT NULL,city TEXT NOT NULL,age INTEGER NOT NULL,password TEXT NOT NULL,coins INTEGER NOT NULL,emoji TEXT NOT NULL,avatar TEXT NOT NULL DEFAULT '',xp INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS rooms(id TEXT PRIMARY KEY,name TEXT NOT NULL,owner TEXT NOT NULL,youtube TEXT,locked BOOLEAN NOT NULL DEFAULT false,created BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS messages(id BIGINT PRIMARY KEY,room_id TEXT NOT NULL,user_id TEXT NOT NULL,name TEXT NOT NULL,kind TEXT NOT NULL,text TEXT NOT NULL,created BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS reports(id TEXT PRIMARY KEY,reporter TEXT NOT NULL,target TEXT,room_id TEXT,reason TEXT NOT NULL,created BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS friends(user_id TEXT NOT NULL,friend_id TEXT NOT NULL,PRIMARY KEY(user_id,friend_id));
CREATE TABLE IF NOT EXISTS notifications(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,text TEXT NOT NULL,created BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS gift_history(id TEXT PRIMARY KEY,sender TEXT NOT NULL,recipient TEXT NOT NULL,gift TEXT NOT NULL,cost INTEGER NOT NULL,created BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS daily_rewards(user_id TEXT PRIMARY KEY,last_claim BIGINT NOT NULL,streak INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS room_playlist(id TEXT PRIMARY KEY,room_id TEXT NOT NULL,video_id TEXT NOT NULL,added_by TEXT NOT NULL,position INTEGER NOT NULL,created BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS bans(id TEXT PRIMARY KEY,room_id TEXT NOT NULL,user_id TEXT NOT NULL,by_user TEXT NOT NULL,reason TEXT NOT NULL,created BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS direct_messages(id TEXT PRIMARY KEY,sender TEXT NOT NULL,recipient TEXT NOT NULL,text TEXT NOT NULL,created BIGINT NOT NULL);
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS private_room BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS code_hash TEXT;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS banned_words TEXT NOT NULL DEFAULT '';
CREATE TABLE IF NOT EXISTS room_images(room_id TEXT PRIMARY KEY,image TEXT NOT NULL,updated BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS room_levels(room_id TEXT PRIMARY KEY,xp INTEGER NOT NULL DEFAULT 0);
ALTER TABLE gift_history ADD COLUMN IF NOT EXISTS room_xp_applied BOOLEAN NOT NULL DEFAULT false;

