CREATE TABLE IF NOT EXISTS ai_bots(room_id TEXT PRIMARY KEY, name TEXT NOT NULL, enabled BOOLEAN NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS ai_daily_usage(day TEXT PRIMARY KEY, requests INTEGER NOT NULL DEFAULT 0);
