ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_frame TEXT NOT NULL DEFAULT 'none';
ALTER TABLE users ADD COLUMN IF NOT EXISTS name_color TEXT NOT NULL DEFAULT 'default';
ALTER TABLE users ADD COLUMN IF NOT EXISTS join_effect TEXT NOT NULL DEFAULT 'none';
ALTER TABLE users ADD COLUMN IF NOT EXISTS bubble_theme TEXT NOT NULL DEFAULT 'default';
