ALTER TABLE users ADD COLUMN IF NOT EXISTS created BIGINT;
UPDATE users SET created = (EXTRACT(EPOCH FROM CURRENT_TIMESTAMP) * 1000)::BIGINT WHERE created IS NULL;
ALTER TABLE users ALTER COLUMN created SET DEFAULT (EXTRACT(EPOCH FROM CURRENT_TIMESTAMP) * 1000)::BIGINT;
